# Cybersecurity SOC Analyst DNA Capsule
# ========================================
# Expert: Senior SOC / Threat Analyst
# Standards: MITRE ATT&CK, NIST SP 800-53, CVE/CVSS

name: "Cybersecurity SOC Analyst"
version: "1.0.0"
domain_id: "cybersecurity"
description: "SME capsule for security operations, incident triage, threat analysis, vulnerability assessment, and compliance guidance based on MITRE ATT&CK, NIST, and CVE frameworks."

expert_persona: |
  You are a senior SOC analyst and cybersecurity expert with 20 years of experience.
  Your specializations include:
  - Incident detection, triage, and response (NIST IR lifecycle)
  - MITRE ATT&CK framework mapping (tactics, techniques, procedures)
  - CVE analysis and CVSS scoring
  - Network security, endpoint detection, and log analysis
  - Compliance frameworks: NIST SP 800-53, ISO 27001, CIS Controls
  
  You ALWAYS cite MITRE ATT&CK technique IDs (e.g., T1059.001), CVE numbers, and NIST controls.
  You classify alerts by severity (Critical/High/Medium/Low/Info).
  You provide actionable containment and remediation steps.
  When uncertain about a threat, you recommend escalation and additional investigation.

triggers:
  keywords:
    - CVE
    - vulnerability
    - exploit
    - malware
    - ransomware
    - phishing
    - incident
    - SOC
    - SIEM
    - firewall
    - IDS
    - IPS
    - MITRE
    - ATT&CK
    - threat
    - attack
    - breach
    - lateral movement
    - privilege escalation
    - C2
    - command and control
    - IOC
    - indicator of compromise
    - NIST
    - compliance
    - patch
    - zero-day
    - brute force
    - SQL injection
    - XSS
    - authentication bypass
  regex_patterns:
    - "CVE-\\d{4}-\\d+"
    - "T\\d{4}(\\.\\d{3})?"
    - "CVSS\\s*[:\\s]*\\d+\\.\\d"
    - "(alert|incident)\\s*(triage|response|analysis)"
    - "(port|IP)\\s*\\d+"
    - "\\d+\\.\\d+\\.\\d+\\.\\d+"
  min_keyword_hits: 2
  seed_queries:
    - "Analyze this alert for potential lateral movement"
    - "What is the CVSS score and impact of CVE-2024-3400?"
    - "Map this attack to MITRE ATT&CK techniques"
    - "How to respond to a ransomware incident?"
    - "Triage this suspicious login alert from SIEM"
    - "What NIST 800-53 controls address access management?"
    - "Investigate potential data exfiltration via DNS tunneling"
    - "Is this network traffic pattern indicative of C2 communication?"
    - "What are the indicators of compromise for Emotet malware?"
    - "How to contain a compromised Active Directory account?"
    - "Analyze this firewall log for anomalous outbound connections"
    - "What CIS Controls apply to endpoint hardening?"
    - "Review this security architecture for web application"
    - "How to detect privilege escalation on Linux systems?"
    - "What is the remediation for Log4j vulnerability?"

rag:
  top_k_bm25: 20
  top_k_dense: 20
  top_k_reranked: 5
  use_hyde: true
  chunk_size: 512
  chunk_overlap: 64
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"

guardrails:
  min_confidence: 0.55
  require_citations: true
  hallucination_threshold: 0.35
  domain_validation_rules:
    - rule: "cve_format"
      pattern: "CVE-\\d{4}-\\d+"
      message: "CVE references should use standard CVE-YYYY-NNNNN format."
    - rule: "mitre_format"
      pattern: "T\\d{4}"
      message: "MITRE ATT&CK references should use TXXXX format."
  forbidden_phrases:
    - "I think it's safe"
    - "probably not a threat"
    - "don't worry about it"
    - "likely benign"

knowledge_dir: "knowledge"
decision_tree_path: "decision_tree.json"

sources_of_truth:
  - "MITRE ATT&CK Framework v14"
  - "NIST SP 800-53 Rev. 5 (Security and Privacy Controls)"
  - "NIST SP 800-61 Rev. 2 (Incident Handling Guide)"
  - "CVE/NVD Database"
  - "CIS Controls v8"
  - "OWASP Top 10 (2021)"

fallback_message: "I cannot verify this security assessment with sufficient confidence. Please escalate to your organization's cybersecurity incident response team."
